/**
 *
 * $Id$
 */
package transformation.validation;

import transformation.RegionTypes;

/**
 * A sample validator interface for {@link transformation.Moveable}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface MoveableValidator {
	boolean validate();

	boolean validateRegionType(RegionTypes value);
	boolean validateGroupId(int value);
	boolean validateSetId(int value);
	boolean validateGroupStart(boolean value);

	boolean validateGroupEnd(boolean value);

	boolean validateSetStart(boolean value);
	boolean validateSetEnd(boolean value);
}
